version: '2'
services:
  db:
    build: db
    #entrypoint: ["pg_restore", "-c", "-d", "bigg", "/src/bigg_database.dump"]
    #command: ["pg_restore", "-c", "-d", "bigg", "/src/bigg_database.dump"]
    ports:
      - "localhost:5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=postgres
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    networks:
      - isolated
  web:
    build: web
    environment:
      - PROCESSES=6
    entrypoint: ["/src/wait-for-it.sh", "db:5432", "-t", "120", "--", "/src/init.sh"]
    ports:
      - "localhost:8910:8910"
    depends_on:
      - db
    networks:
      - isolated
      
networks:
  isolated:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"